[package]
name = "local-jev-core"
version = "0.2.4"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
indexmap = { workspace = true }
aquamarine = "0.6.0"
utoipa = { workspace = true, optional = true }

[features]
openapi = ["dep:utoipa", "utoipa/indexmap"]
