[package]
name = "local-jev-runtime"
version = "0.2.0"
edition = "2024"

[dependencies]
aquamarine = "0.6.0"
local-jev-core = { workspace = true }
tokenizers = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
ort = { workspace = true }
ndarray = { workspace = true }
tracing = { workspace = true }

[features]
default = []
coreml = ["ort/coreml"]
cuda = ["ort/cuda"]
tensorrt = ["ort/tensorrt"]
